#!/usr/bin/bash
# GPL v3.0
# Made by Sarkans (Sergei Vishnevecki)
#
# |----  Fast debugger for C++  ----|
# |                                 |
# |  This script is used for fast   |
# |   compiling your C/C++ source   |
# |       code. C++ version.        |
# |                                 |
# |---------------------------------|

_S0="\033[0m"
_CRED="\033[31m"
_CGRN="\033[32m"
_CYLW="\033[33m"
_CBLU="\033[34m"
_CPRP="\033[35m"
_CCYN="\033[36m"
_CWHT="\033[37m"
_SBLD="\033[1m"
_SITL="\033[3m"

echo -e "${_SBLD}[ ${_CYLW}Fast Debugger${_CWHT} ] C++${_S0}"

echo -e "${_SITL}${_CCYN}Compiling files...${_S0}\n"
g++ -o a.out -Wall -I ./lib/ ./src/*.cpp
if [ ! -f ./a.out ]; then
    echo -e "${_CRED}[1]${_S0}: Source code was not compiled."
else
    chmod +x ./a.out
    ./a.out
    rm ./a.out
    echo -e "\n${_CGRN}[0]${_S0}: Successful."
fi