#!/usr/bin/env bash
# GPL v3.0
# Made by Sarkans (Sergei Vishnevecki)
#
# |--------  Fust Builder  ---------|
# |                                 |
# |  This script is used for fast   |
# |   compiling your C/C++ source   |
# |       code. C++ version.        |
# |                                 |
# |---------------------------------|

# Constannts
_S0="\033[0m"
_CRED="\033[31m"
_CGRN="\033[32m"
_CYLW="\033[33m"
_CBLU="\033[34m"
_CPRP="\033[35m"
_CCYN="\033[36m"
_CWHT="\033[37m"
_SBLD="\033[1m"
_SITL="\033[3m"
_CODE_ERROR="[${_CRED}${_SBLD}1${_S0}]"
_CODE_SUCCESS="[${_CGRN}${_SBLD}0${_S0}]"

# Variables
dbgn="progdebug"
rlsn="progrelease"
path="$(pwd)/\ "
echo "pwd = ${path}"

case $1 in
    "help")
        echo -e "${_CYLW}${_SBLD}Fust Builder manual${_S0}\n"
        echo -e "fust ${_CCYN}[ARGUMENT_1] ${_CPRP}[ARGUMENT_2]${_S0}:"
        echo -e "\t${_CCYN}[ARGUMENT_1]${_S0}"
        echo -e "\t\t${_CYLW}help${_S0}\t\t---   Display this manual."
        echo -e "\t\t${_CYLW}debug${_S0}\t\t---   Perform debugging. Creates an executable file in the project folder at 'project-path/build/debug/' and runs it immediately."
        echo -e "\t\t${_CYLW}pdebug${_S0}\t\t---   Pure debugging. Does the same as 'debug', but leaves no executable files behind."
        echo -e "\t\t${_CYLW}build${_S0}\t\t---   Builds the project into an executable file at 'project-path/build/release/'."
        ;;
    "pdebug")
        case $2 in
            "cpp")
                echo -e "${_SBLD}[ ${_CYLW}Fust Builder${_CWHT} ] C++${_S0}"
                echo -e "${_SITL}${_CCYN}Compiling files...${_S0}\n"
                g++ -o "${dbgn}" -Wall -I ${path}/lib/ ${path}/src/*.c* -lm
                if [ ! -f ./${dbgn} ]; then
                    echo -e "Fust ${_CODE_ERROR}: Source code was not compiled."
                else
                    chmod +x ./${dbgn}
                    "${dbgn}"
                    rm ./${dbgn}
                    echo -e "\nFust ${_CODE_SUCCESS}: Successful."
                fi
                ;;
            *)
                echo -e "Fust ${_CODE_ERROR}: Wrong argument '$2'."
                ;;
        esac
        ;;
    *)
        echo -e "Fust ${_CODE_ERROR}: Wrong argument '$1'."
        ;;
esac
